- Hey, my name is Neku. I'm a placeholder from the game The World Ends With You. #side:right #position:0 #speaker:Neku #animation:neku_idle
- My head hurts. Let's test the portrait-swapping feature. #animation:neku_injured
- Like I said, I'm just a placeholder. Get out of here!
- Ok Neku, sounds good. Nice to meet you. #side:left #position:0 #speaker:Ivy #animation:ivy_idle
- Agggh! #side:right #position:0 #speaker:Neku
    -> END
